### ISSUE TITLE
Air quality detector using API

### ISSUE THREAD

**Issue by muddhit** [Mukulbaid63/Hack-with-JavaScript#1]
Use the api :https://api.weatherbit.io/v2.0/,detect the current location and display the parameters on screen

**Comment by RohithChittibommala** [comment]
I want work on this issue

**Comment by abhisheklalwani26** [comment]
Can I work on this?

**Comment by muddhit** [comment]
@abhisheklalwani26 yes go for it

**Comment by abhisheklalwani26** [comment]
https://github.com/abhisheklalwani26/AQI

**Comment by muddhit** [comment]
@abhisheklalwani26 Please create a PR
