### ISSUE TITLE
Add Pull Request,Issue template and a welcome bot

### ISSUE THREAD

**Issue by m-code12** [Mukulbaid63/Hack-with-JavaScript#15]
We can add an issue and a PR template for the contributors.

@Mukulbaid63 I would like to work on this as a part of CrossWoc 2021. Can you assign it to me?

**Comment by muddhit** [comment]
@m-code12 you can work on it but it's not a part of CrossWoc

**Comment by m-code12** [comment]
> @m-code12 you can work on it but it's not a part of CrossWoc

As in the project is not a part of CrossWoc ?
I would also like to add a welcome bot something similar to 

> ## Demo 1
> ![](https://user-images.githubusercontent.com/13410355/28288547-5f83aa8e-6af4-11e7-9692-eb41d42431e2.png)
> 
> ## Demo 2
> ![](https://user-images.githubusercontent.com/2440938/89543720-44299780-d7cf-11ea-82a0-bd81664f0d8e.png)

**Comment by muddhit** [comment]
Ya go for it @m-code12

**Comment by m-code12** [comment]
Yeah I am working on this, could you add the level tag and CrossWoc tag?

**Comment by muddhit** [comment]
Actually @m-code12 These project isn't associated with CrossWoc any more,but if you want to keep the open source spirit you can still contribute, i will be considering the early contributors for further events and opportunities
