### ISSUE TITLE
Analog Clock

### ISSUE THREAD

**Issue by muddhit** [Mukulbaid63/Hack-with-JavaScript#25]

**Comment by supzi-del** [comment]
![Screenshot (51)](https://user-images.githubusercontent.com/78655439/108504575-1d9afc00-72dc-11eb-98e7-fac187a25719.png)
Check this out!

**Comment by muddhit** [comment]
@supzi-del are you going to work on it?

**Comment by supzi-del** [comment]
Shall I send a PR for the above analog clock?

**Comment by muddhit** [comment]
> Shall I send a PR for the above analog clock?

Yeah sure
