### ISSUE TITLE
Currency Converter app

### ISSUE THREAD

**Issue by muddhit** [Mukulbaid63/Hack-with-JavaScript#4]

**Comment by RohithChittibommala** [comment]
I want to work on this issue

**Comment by muddhit** [comment]
Go for it!

**Comment by Harshal0902** [comment]
@Mukulbaid63 Can you please assign this issue to me?
I would like to work on this issue.

**Comment by muddhit** [comment]
@Harshal0902 go on!

**Comment by Harshal0902** [comment]
@Mukulbaid63 How many types of currency do you want me to add?

**Comment by muddhit** [comment]
60 approx.
