### ISSUE TITLE
CLI Calculator

### ISSUE THREAD

**Issue by muddhit** [Mukulbaid63/Hack-with-JavaScript#8]

**Comment by jzandag** [comment]
can you assign this to me?

**Comment by muddhit** [comment]
@jzandag Sure!, go for it, but please maintain the PR in a folder, with a README.md file(which should contain working screenshots and a brief intro!!)

**Comment by jzandag** [comment]
Thanks!

**Comment by muddhit** [comment]
@jzandag  good work, but this repo is for Vanilla JS apps, Can you make it using Vanilla JS
